branch-defaults:
  master:
    environment: handson-2010037a-production
  staging:
    environment: handson-2010037a-staging
global:
  application_name: handson-2010037
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-1
  profile: eb-cli
  sc: git
